# -*- coding: utf-8 -*-
{
    'name': 'Parc Erp',
    'version': '11.0.4',
    'author': 'Softifi',
    'summary': 'Zarzis Park Erp System',
    'sequence': -10,
    'description': """Zarzis Park Erp System Module""",
    'category': 'Zarzis Park Erp',
    'depends': ['base', 'mail', 'product', 'website', 'portal'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'report/rental_submission_report_accept.xml',
        'report/rental_submission_report_validate.xml',
        'report/rental_submission_report_application.xml',
        'data/refuse_rental_request_email_template.xml',
        'data/accept_rental_request_email_template.xml',
        'data/validate_rental_request_email_template.xml',
        'data/send_mail_before_expire_email_template.xml',
        'wizard/email_compose_message_wizard_inherit.xml',
        'views/local_view.xml',
        'views/company_changes_view.xml',
        'views/main.shareholders.xml',
        'views/partner_view.xml',
        'views/rental_submission_view.xml',
        'views/menu.xml',

    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
